#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v16
# autospec commit: b858a2a
#
Name     : R-audio
Version  : 0.1.11
Release  : 2
URL      : https://cran.r-project.org/src/contrib/audio_0.1-11.tar.gz
Source0  : https://cran.r-project.org/src/contrib/audio_0.1-11.tar.gz
Summary  : Audio Interface for R
Group    : Development/Tools
License  : MIT
Requires: R-audio-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package lib
Summary: lib components for the R-audio package.
Group: Libraries

%description lib
lib components for the R-audio package.


%prep
%setup -q -n audio

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1721073220

%install
export SOURCE_DATE_EPOCH=1721073220
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/audio/DESCRIPTION
/usr/lib64/R/library/audio/INDEX
/usr/lib64/R/library/audio/LICENSE
/usr/lib64/R/library/audio/Meta/Rd.rds
/usr/lib64/R/library/audio/Meta/features.rds
/usr/lib64/R/library/audio/Meta/hsearch.rds
/usr/lib64/R/library/audio/Meta/links.rds
/usr/lib64/R/library/audio/Meta/nsInfo.rds
/usr/lib64/R/library/audio/Meta/package.rds
/usr/lib64/R/library/audio/NAMESPACE
/usr/lib64/R/library/audio/NEWS
/usr/lib64/R/library/audio/R/audio
/usr/lib64/R/library/audio/R/audio.rdb
/usr/lib64/R/library/audio/R/audio.rdx
/usr/lib64/R/library/audio/help/AnIndex
/usr/lib64/R/library/audio/help/aliases.rds
/usr/lib64/R/library/audio/help/audio.rdb
/usr/lib64/R/library/audio/help/audio.rdx
/usr/lib64/R/library/audio/help/paths.rds
/usr/lib64/R/library/audio/html/00Index.html
/usr/lib64/R/library/audio/html/R.css

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/audio/libs/audio.so
